In [1]:
# From a Python list  1d
import numpy as np
a = np.array([1, 2, 3])
print(a)  
print(type(a))  


[1 2 3]
<class 'numpy.ndarray'>


In [6]:
#2d
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)
print(type(b))


[[1 2 3 4]
 [5 6 7 8]]
<class 'numpy.ndarray'>


In [3]:
#3d
c=np.array([[[1,2],[3,4],[4,5]]])
print(c)
type(c)

[[[1 2]
  [3 4]
  [4 5]]]


numpy.ndarray

In [7]:
#array oprsn
import numpy as np
data=np.array([1,2])
ones=np.ones(2, dtype=int)
print(data + ones) 
print(data - ones)  
print(data * data) 
print(data / data)  



[2 3]
[0 1]
[1 4]
[1. 1.]


In [8]:
#Basic array oprsn
a=np.array([1,2,3,4])
print(a.sum())

10


In [9]:
#mean
print(a.mean())

2.5


In [10]:
#sum by axis for 2d array
b = np.array([[1, 1], [2, 2]])
print(b.sum(axis=0)) 
print(b.sum(axis=1))  


[3 3]
[2 4]


In [11]:
#spcl arrays
np.zeros((2, 3))    
np.ones((1, 4))     
np.full((3, 3), 7)  
np.eye(3)           
np.random.random((2, 2))  

array([[0.89657402, 0.93815656],
       [0.95732601, 0.54698961]])